add pyproject configuration
The check script complains with

  Running mypy... src/python/zfs-snap.py:6: error: Skipping analyzing
  "websocket": module is installed, but missing library stubs or py.typed
  marker [import-untyped]

due to missing configuration.

Signed-off-by: Daniel Wagner <wagi@monom.org>